name: CI Pipeline

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust the Node.js version if needed

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Build the application
      - name: Build the app
        run: npm run build

      # Upload the build as an artifact (optional)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      # Deploy (Optional step if you want to deploy automatically after build)
      # You can add deployment steps here if you are deploying to a service like Netlify, Vercel, or Firebase.
