name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Echo test
      - name: Echo test
        run: echo "Hello, world!"

      # Step 2: Check out the repository
      - uses: actions/checkout@v4

      # Step 3: Run a one-line script
      - name: Run a one-line script
        run: echo Hello, world!

      # Step 4: Run a multi-line script
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
